name: apex

channels:
  - pytorch

dependencies:
  - python=3.8
  - pytorch
  - jupyter
  - ipython
  - numpy
  - matplotlib
  - tqdm
  - scipy
  - pandas
  - lxml
  - pip
  - pip:
    - ray
    - ray[debug]
    - tensorboard